import Head from 'next/head'
import Link from 'next/link';
import Date from '../components/date';
import { getSortedPostsData } from '../lib/posts';
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram, AiFillGithub } from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}


export default function Home({ allPostsData }) {
  const [darkMode, setDarkMode] = useState(true)
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Doni Wirawan portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>Doni Wirawan</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-xl' /></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#" target="_blank" rel="noopener noreferrer">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-teal-500 font-medium md:text-6xl'>Doni Wirawan</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer & Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-500'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias aliquid ea perferendis incidunt, nesciunt eum eligendi, molestias culpa cum optio ullam consequatur quaerat natus mollitia reiciendis accusamus corporis sunt in.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-500'>
            <AiFillGithub />
            <AiFillInstagram />
            <AiFillLinkedin />
            <AiFillTwitterCircle />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 font-bold lg:text-center mt-4'>Services I Offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, error modi iusto sequi sunt dolore ipsa facere unde a quaerat.</p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, error modi iusto sequi sunt dolore ipsa facere unde a quaerat.</p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 '>
              <Image src={design} width={100} height={100} className='m-auto'></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2 '>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet ex, facilis est, doloribus alias qui aliquam nulla earum distinctio sunt provident deleniti velit omnis libero adipisci repellat. Error, quia velit.</p>
              <h4 className='py-4'>Design tools that i use:</h4>
              <p className="text-gray-800 py-1 dark:text-gray-500">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-500">Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 '>
              <Image src={code} width={100} height={100} className='m-auto'></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'>Working Code</h3>
              <p className='py-2 '>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet ex, facilis est, doloribus alias qui aliquam nulla earum distinctio sunt provident deleniti velit omnis libero adipisci repellat. Error, quia velit.</p>
              <h4 className='py-4'>Design tools that i use:</h4>
              <p className="text-gray-800 py-1 dark:text-gray-500">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-500">Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 '>
              <Image src={consulting} width={100} height={100} className='m-auto'></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'>Consulting</h3>
              <p className='py-2 '>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Amet ex, facilis est, doloribus alias qui aliquam nulla earum distinctio sunt provident deleniti velit omnis libero adipisci repellat. Error, quia velit.</p>
              <h4 className='py-4'>Design tools that i use:</h4>
              <p className="text-gray-800 py-1 dark:text-gray-500">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-500">Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 font-bold lg:text-center'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, error modi iusto sequi sunt dolore ipsa facere unde a quaerat.</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
          </div>
        </section>
        <section >
          <h3 className='text-3xl py-1 font-bold lg:text-center mt-4'>Blog</h3>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500 lg:text-center'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, error modi iusto sequi sunt dolore ipsa facere unde a quaerat.</p>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            {allPostsData.map(({ id, date, title }) => (
              <Link href={`posts/${id}`}>
                <div key={id} className="basis-1/3 flex-1 shadow-lg p-5 rounded-xl">
                  <h4 className='text-lg font-medium '>{title}</h4>
                  <p className='text-gray-500'><Date dateString={date} /></p>
                </div>
              </Link>
            ))}
          </div>
        </section>
      </main>
    </div >

  )
}
